dataset: 'Hospital'
scenes: [ 'front' ]


front:
  n_cluster: 128
  cluster_mode: 'xy'
  cluster_method_: 'kmeans'
  cluster_method: 'birch'

  training_sample_ratio: 1
  eval_sample_ratio: 10
  gt_pose_path: 'queries_poses.txt'
  query_path: 'queries_with_intrinsics.txt'
  image_path_prefix: ''